### ISSUE TITLE
Request: Add Carthage Support

### ISSUE THREAD

**Issue by rzulkoski** [Slyce-Inc/Slyce-iOS-SDK#4]
We use Carthage for our dependency management rather than CocoaPods. Would it be possible for you to add Carthage support in a future release?

**Comment by NexShawJobs** [comment]
We are also trying to use Carthage on Slyce. Any update on this?

**Comment by amrox** [comment]
Carthage is supported for versions 5.1.0 and higher: https://github.com/Slyce-Inc/Slyce-iOS-SDK/pull/12
