### ISSUE TITLE
Request: SFCameraView turnFlash(_:) should set flash mode and not torch mode.

### ISSUE THREAD

**Issue by mlarandeauHay** [Slyce-Inc/Slyce-iOS-SDK#5]
The current implementation of turnFlash(_:) on SFCameraView is actually just toggling the device torch on and off and not using the actual camera flash.  When taking photos, I believe that the camera flash is much more desirable and expected from a user perspective than toggling the torch.  Furthermore, I would expect to be able to set the value to any of the cases in AVCaptureDevice.FlashMode.

**Comment by amrox** [comment]
Better late than never - even though this applies to SDK 4 - I've logged this request into our internal system. Thanks for the feedback!
